require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'lib/*'
    - 'vendor/**/*'
    - 'test/**'
  SuggestExtensions: false

Rails:
  enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false
