version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers-legacy
        environment:
          - BUNDLER_VERSION: 1.17.2
          - RAILS_ENV: 'test'
          - DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          - MYSQL_USER: user
          - MYSQL_DB: jtpcn_test
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: wait for database
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 5m

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            gem install bundler -v 1.17.2
            bundle install --path=vendor/bundle --jobs 4 --retry 3

      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Use specific database.yml
          command: mv config/database.yml.ci config/database.yml

      - run:
          name: Database Setup
          command: |
            
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: Rspec
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - store_test_results:
          path: /tmp/test-results

  deploy:
    docker:
      - image: buildpack-deps:trusty
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Heroku deploy
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2.1
  build-deploy:
    jobs:

      - build
      - deploy:
          requires:
            - build
