default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: jptcn_development

test:
  <<: *default
  database: jtpcn_test
  host: <%= ENV['MYSQL_ROOT_HOST'] || '127.0.0.1' %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  url: <%= ENV['DB_URL'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>

